### ISSUE TITLE
Error:  module is a string value; tsconfig JSON must be parsed with parseJsonSourceFileConfigFileContent or getParsedCommandLineOfConfigFile before passing to createProgram

### ISSUE THREAD

**Issue by vernaillen** [vernaillen/wpnuxt-module#134]
since PR #129 was merged, the follow error occurs during pnpm build:

```
Error:  module is a string value; tsconfig JSON must be parsed with parseJsonSourceFileConfigFileContent or getParsedCommandLineOfConfigFile before passing to createProgram
  at Object.createProgram (node_modules/.pnpm/typescript@5.5.2/node_modules/typescript/lib/typescript.js:123997:15)
  at getDeclarations (node_modules/.pnpm/mkdist@1.5.2_typescript@5.5.2_vue-tsc@2.0.21/node_modules/mkdist/dist/index.mjs:302:22)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async mkdist (node_modules/.pnpm/mkdist@1.5.2_typescript@5.5.2_vue-tsc@2.0.21/node_modules/mkdist/dist/index.mjs:526:35)
  at async mkdistBuild (node_modules/.pnpm/unbuild@2.0.0_typescript@5.5.2_vue-tsc@2.0.21/node_modules/unbuild/dist/index.mjs:927:22)
  at async _build (node_modules/.pnpm/unbuild@2.0.0_typescript@5.5.2_vue-tsc@2.0.21/node_modules/unbuild/dist/index.mjs:1086:3)
  at async build (node_modules/.pnpm/unbuild@2.0.0_typescript@5.5.2_vue-tsc@2.0.21/node_modules/unbuild/dist/index.mjs:945:5)
  at async Object.run (node_modules/.pnpm/@nuxt+module-builder@0.8.0_@nuxt+kit@3.12.2_nuxi@3.12.0_typescript@5.5.2_vue-tsc@2.0.21/node_modules/@nuxt/module-builder/dist/chunks/build.mjs:43:5)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:3[16](https://github.com/vernaillen/wpnuxt-module/actions/runs/9625279744/job/26549993605#step:9:17):16)
  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
```

This seems to be the same issue as this: 
https://github.com/nuxt/module-builder/issues/297

**Comment by vernaillen** [comment]
This is caused by the Typescript update to 5.5.2.  The error is gone after downgrading Typescript to 5.4.5
